### ISSUE TITLE
Move shared code into external library

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/jupyter_rs_radia#13]
The radia and vtk widgets use some of the same routines.  These live in their own files like ```gui_utils.py``` but the files are duplicated for each widget.  We should make a package for them, with an eye toward reusing them in Sirepo

**Comment by mkeilman** [comment]
Suspending work on this, but as sirepo work begins it will be useful to have as a reminder...

**Comment by robnagler** [comment]
too old to be relevant
