### ISSUE TITLE
widget freezes intermittently

### ISSUE THREAD

**Issue by dtabell** [radiasoft/jupyter_rs_radia#31]
In developing [Radia Example #5](
https://github.com/radiasoft/Radia-Examples/blob/master/Radia_Ex05.ipynb)
I restarted the kernel multiple times, and at some point I found that the
three-dimensional image of the magnet would no longer rotate, and would
not respond to changes in the surface alpha slider.

This problem persisted across kernel restarts, as well as across server restarts.

After moving to the beta server, the widget appeared to be working again;
but then later the problem appeared on the beta server as well. At that point
I stopped both servers, did something else for a while, and returned to test
this again an hour or two later. Now working again.

**Comment by robnagler** [comment]
still an issue?
