### ISSUE TITLE
Fix wayward beam axis line

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/jupyter_rs_radia#42]
The beam axis has a few annoyances:

- [ ] does not always refresh properly
- [ ] gets confused if the endpoints are the same
- [ ] goes through the center of the collection of objects, not (0, 0, 0) in lab coords

Same issues in the sirepo version

**Comment by robnagler** [comment]
relevant?

**Comment by mkeilman** [comment]
Closing, not of much importance
