### ISSUE TITLE
Adapt field arrow sizes to the extents of the geometry

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/jupyter_rs_radia#45]
The arrows are currently resized by a fixed constant which can make them too large or small.  The sirepo version is also implementing this, so I wanted to get a corresponding issue in place here.

**Comment by robnagler** [comment]
Relevant?

**Comment by mkeilman** [comment]
> Relevant?

No, don't think so. It's cosmetic.

**Comment by robnagler** [comment]
Please close if irrelevant...

**Comment by mkeilman** [comment]
A cosmetic change; closing
